# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd64aa4e1d5a139c94c114e562197a13375e673f4af8c5463ba9cb717f45f694e9783772a7e572aa0fad64ec7b5bddc9eb6f545f4cd43e7805838803b149d98a

test:
  secret_key_base: c12ba0fc163bc16f6ab992fa0c2215c32a2c721a7dfad893fabb1674970bacb80e92e773394a035f27fba71c03c68449cfa4e80235232143051defc35b5d043a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
